"use strict";
let lname;
lname = "khalil";
let newname = lname.toUpperCase();
console.log(newname);
let age;
age = 25;
let dob = "25";
let result = parseInt(dob);
let isValid;
isValid = false;
console.log(isValid);
let empList;
empList = ["khalil", "mike"];
console.log(empList);
let numList;
numList = [1, 2, 3, 4];
let result2 = numList.filter((num) => num > 2);
console.log(result2);
